import { SKILLS, UPGRADES, CARDS, ENEMIES, RELICS, ROUTE, FACE_NAME, type Face, type SkillId } from './data.js';
import { newRun, dispatch, serialize, deserialize, symbol, skillFor, payment, preview, canSkill, incoming, price, rewardLegal, type State, type Action, type Reward } from './engine.js';

const app=document.querySelector<HTMLElement>('#app')!;
const modal=document.querySelector<HTMLDialogElement>('#modal')!;
const KEY='ember-dungeon-save-v1', PREF='ember-dungeon-settings-v1';
let state:State|null=null, corrupt:string|null=null, saveWarning='', offlineReady=false;
let settings={sound:false,quick:false};
let selection: {kind:'skill';id:SkillId;dice:number[]}|{kind:'card';id:number;die:number;face:Face}|null=null;
let toastTimer:ReturnType<typeof setTimeout>;
const escape=(v:unknown)=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const icon=(face:Face|'any')=>({sword:'⚔',shield:'⬟',fire:'♨',any:'✧'}[face]);
const symbolHTML=(face:Face|'any')=>`<span class="symbol ${face}" aria-label="${FACE_NAME[face]}">${icon(face)}</span>`;
const button=(text:string,action:string,cls='',disabled=false,extra='')=>`<button class="${cls}" data-action="${action}" ${disabled?'disabled':''} ${extra}>${text}</button>`;
const faceRow=(faces:(Face|'any')[])=>faces.map(symbolHTML).join('');
const skillText=(skill:ReturnType<typeof skillFor>)=>`${skill.damage?`${skill.damage} ${skill.pierce?'穿透伤害':'伤害'}`:''}${skill.damage&&skill.block?' · ':''}${skill.block?`${skill.block} 格挡`:''}${skill.next?` · 下次攻击 +${skill.next}`:''}`;
try {const raw=localStorage.getItem(KEY);if(raw){try{state=deserialize(raw);}catch{corrupt=raw;}}const pref=JSON.parse(localStorage.getItem(PREF)||'{}');settings={sound:pref.sound===true,quick:pref.quick===true};} catch {saveWarning='浏览器未允许本地存储，请及时导出进度。';}
function notify(text:string){const el=document.querySelector<HTMLElement>('#toast')!;el.textContent=text;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),3200);}
function persist(next:State){try{localStorage.setItem(KEY,serialize(next));saveWarning='';}catch{saveWarning='进度仅在本次打开中保留，请从菜单导出存档。';}state=next;}
let audio:AudioContext|null=null;
function sound(){if(!settings.sound)return;try{audio ||=new AudioContext();void audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.connect(g);g.connect(audio.destination);o.type='sine';o.frequency.setValueAtTime(440,audio.currentTime);o.frequency.exponentialRampToValueAtTime(220,audio.currentTime+.09);g.gain.setValueAtTime(.035,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.13);o.start();o.stop(audio.currentTime+.14);}catch{/* Sound is optional. */}}
function act(a:Action){if(!state)return;try{const next=dispatch(state,a);persist(next);close();render();sound();if(a.type==='roll'&&!settings.quick)app.querySelector('.dice-tray')?.classList.add('toss');}catch(e){notify(e instanceof Error?e.message:'操作未完成。');}}
function close(){modal.close();selection=null;}
function open(content:string){modal.innerHTML=`<div class="modal-top"><span class="eyebrow">余烬手记</span>${button('×','close','icon-btn',false,'aria-label="关闭详情"')}</div>${content}`;if(!modal.open)modal.showModal();}
function header(){return `<header class="topbar"><div class="wordmark"><span>⟐</span> 骰子地下城 <small>DEMO</small></div>${button('☰','menu','icon-btn',false,'aria-label="打开菜单"')}</header>`;}
function stats(){return `<div class="resources"><span class="health">♥ <b>${state!.hp}</b><small> / ${state!.maxHp}</small></span><span class="gold">◉ ${state!.gold}</span>${button(`◈ 构筑 ${state!.relics.length+Object.keys(state!.upgrades).length+state!.dice.filter(d=>d.modified).length}`,'build','text-btn')}<span class="floor">${Math.min(7,state!.floor+1)} / 7 层</span></div>`;}
function portrait(enemy='boss'){
  const flame=enemy==='priest'||enemy==='boss', horns=enemy==='hunter'||enemy==='elite';
  return `<svg class="portrait" viewBox="0 0 220 170" aria-hidden="true"><defs><radialGradient id="aura"><stop stop-color="${flame?'#b1693b':'#567c69'}" stop-opacity=".5"/><stop offset="1" stop-color="#17211e" stop-opacity="0"/></radialGradient><linearGradient id="armor" x2="1" y2="1"><stop stop-color="#658071"/><stop offset=".5" stop-color="#2f4940"/><stop offset="1" stop-color="#182a26"/></linearGradient></defs><circle cx="110" cy="88" r="83" fill="url(#aura)"/><circle cx="110" cy="85" r="63" fill="none" stroke="#b59865" stroke-opacity=".18"/><path d="M25 162 58 121 84 109h53l26 12 31 41" fill="#111b19" stroke="#5a7261"/><path d="m61 124 19-13 31 21 30-21 20 13-19 39H77Z" fill="url(#armor)" stroke="#7c8970"/><path d="m110 133-11 15 11 16 11-16Z" fill="#deac6b"/><path d="m73 53 37-21 37 21-5 51-32 29-32-29Z" fill="url(#armor)" stroke="#99a489" stroke-width="1.7"/><path d="m76 72 34 13 34-13-5 31-29 22-29-22Z" fill="#101d19"/><path d="m84 82 18 6-1 5-16-5m50-6-18 6 1 5 16-5" fill="#ffc77e"/><path d="m110 36-8 38 8 11 8-11Z" fill="#b6b28a"/><path d="m109 95-7 23 8 6 8-6-7-23" fill="#556e5b"/>${horns?'<path d="M78 57 50 25 55 67 79 78m63-21 28-32-5 42-24 11" fill="#526c59" stroke="#a4a785"/>':''}${flame?'<path d="m96 36 1-25 13 12 9-21 8 34-17-4Z" fill="#d0a169"/><path d="m161 122 11-21 5 17 12-10-5 26" fill="#be793e"/>':''}<path d="M43 158 62 94 69 92 59 162" fill="#8a9478"/><path d="m54 130 23 5" stroke="#c3ae7c" stroke-width="4"/><g fill="#d1a468" opacity=".6"><circle cx="45" cy="73" r="1.8"/><circle cx="171" cy="58" r="1.2"/><circle cx="150" cy="25" r="1.5"/><circle cx="62" cy="102" r="1"/></g></svg>`;
}
function home(){return `${header()}<section class="home"><div class="chapter">第一幕 / THE EMBER DESCENT</div><h1>六枚命骰<br>一线<span>余烬</span></h1><p class="lead">深入地城。保留希望。<br>让每一次收手，都成为你的选择。</p><div class="hero-art">${portrait()}<div class="hero-seal">Ⅰ</div></div><div class="hero-name">余烬骑士 <span>60 生命 · 六骰 · 双技能</span></div><div class="home-rules"><span><b>01</b> 掷骰与保留</span><span><b>02</b> 分配两招</span><span><b>03</b> 构筑与深入</span></div>${corrupt?'<div class="warning">发现不兼容或损坏的旧存档。可在菜单导出原文件；不会自动覆盖。</div>':''}${button('点燃余烬，开始旅途 <span>→</span>','new','primary wide')}${button('第一次来？看看玩法','help','text-btn wide')}<small class="footnote">单人 PVE · 约 10–20 分钟试玩 · 自动保存<br>当前为开发 Demo，时长与平衡待实测</small></section>`;}
function mapView(){return `<section class="map-view"><div class="section-heading"><span class="eyebrow">CHAPTER 01 · 灰烬地城</span><h1>向火而行<span>已通过 ${state!.floor} 层</span></h1><p>生命会带入下一场战斗。每一步，都留下痕迹。</p></div><div class="route">${ROUTE.map((nodes,i)=>`<div class="route-row ${i===state!.floor?'current':i<state!.floor?'complete':'future'}"><div class="route-number">${i<state!.floor?'✓':String(i+1).padStart(2,'0')}</div><div class="route-options">${nodes.map((n,j)=>button(`<span class="node-symbol">${n.id==='boss'?'♜':n.type==='camp'?'♨':n.type==='shop'?'◉':n.type==='event'?'✧':n.id==='elite'?'♛':'⚔'}</span><span><b>${n.name}</b><small>${n.text}</small></span>${i===state!.floor?'<span class="arrow">→</span>':''}`,`enter:${j}`,`route-node ${state!.path[i]===n.id?'chosen':''}`,i!==state!.floor)).join('')}</div></div>`).join('')}</div><div class="boss-note"><span>♜</span><div><b>前方：铸命者</b><p>半血强化后，第二次普通重掷失去 2 生命。${button('查看机制','boss-info','inline-btn')}</p></div></div></section>`;}
function missing(id:SkillId){const sk=skillFor(state!,id),pool=state!.dice.filter(d=>!d.spent).map(symbol),miss:string[]=[];for(const f of sk.cost){const i=f==='any'?(pool.length?0:-1):pool.indexOf(f);if(i>=0)pool.splice(i,1);else miss.push(FACE_NAME[f]);}return miss.join('');}
function battleView(){const s=state!,b=s.battle!,enemy=ENEMIES[b.enemy],rolling=b.phase==='roll';return `<section class="battle-view">
  <div class="encounter"><div class="enemy-label"><span class="eyebrow">${b.enemy==='boss'?'幕末首领':b.enemy==='elite'?'精英遭遇':'地城遭遇'} <span>回合 ${b.turn}</span></span><h1>${enemy.name}${button('ⓘ','enemy-info','info-btn',false,'aria-label="查看敌人机制"')}</h1><div class="enemy-hp"><span style="width:${b.hp/b.maxHp*100}%"></span></div><div class="hp-text">${b.hp} / ${b.maxHp} <span>${b.block?`⬟ 格挡 ${b.block}`:''}</span></div></div>${portrait(b.enemy)}</div>
  <div class="intent"><span class="intent-icon">${b.intent.attacks.length?'⚔':b.intent.block?'⬟':'◌'}</span><div><b>${b.intent.name}</b> <span>${b.intent.attacks.length?(b.intent.attacks.length>1?b.intent.attacks.join(' + ')+' 连击':b.intent.attacks[0]+' 伤害'):b.intent.block?`获得 ${b.intent.block} 格挡`:'本回合不攻击'}</span><small>${b.enhanced?'铸命税：第二次普通重掷 −2 生命':'意图固定，敌人在你行动后执行'}</small></div><div class="forecast"><b>${incoming(s)}</b><small>预计受伤</small></div></div>
  <div class="board-heading"><span>骑士技艺 <small>${rolling?'收手后发动':'选择技能，预览后确认'}</small></span><span class="slots"><i class="${b.used.length>0?'filled':''}"></i><i class="${b.used.length>1?'filled':''}"></i> ${b.used.length}/2 招</span></div>
  <div class="skill-grid">${SKILLS.map(base=>{const sk=skillFor(s,base.id),paid=b.used.includes(base.id),possible=payment(s,base.id)!==null;return button(`<span class="skill-top"><b>${sk.name}</b><span class="cost">${faceRow(sk.cost)}</span></span><span class="skill-effect">${skillText(sk)}</span><small>${paid?'✓ 本回合已使用':!b.rolls?'等待掷骰':possible?rolling?'组合已满足':'点击预览消耗':`缺少：${missing(sk.id)}`}${s.upgrades[sk.id]!==undefined?' · 已升级':''}</small>`,`skill:${sk.id}`,`skill ${paid?'spent':possible&&b.rolls?'ready':''} ${sk.id==='inferno'?'ultimate':''}`);}).join('')}</div>
  <div class="dice-heading"><span>${!b.rolls?'六枚命骰，等待落定':rolling?'点击骰子保留 ◇':'灰色骰子已被消耗'}</span><span>${b.rolls?`重掷 ${b.rolls-1}/2`:'首次投掷'} · ⬟ ${s.block} 格挡</span></div>
  <div class="dice-tray">${s.dice.map(d=>button(`${b.rolls?symbolHTML(symbol(d)):'<span class="unrolled">?</span>'}<small>${d.spent?'已用':d.held?'◆ 保留':`骰 ${d.id+1}`}</small>`,`die:${d.id}`,`die ${d.held?'held':''} ${d.spent?'spent':''} ${d.modified?'modified':''}`,!rolling||!b.rolls,`aria-label="骰 ${d.id+1}${b.rolls?' '+FACE_NAME[symbol(d)]:''}${d.held?' 已保留':''}${d.spent?' 已消耗':''}" aria-pressed="${d.held}"`)).join('')}</div>
  <div class="cards-heading"><span>战术牌 <b>◈ ${b.tp}</b> <small>已用 ${b.cardsUsed}/2</small></span><small>牌库 ${b.deck.length} · 弃牌 ${b.discard.length}</small></div>
  <div class="hand">${b.hand.map(c=>button(`<span>${CARDS[c.kind].name}</span><b>${CARDS[c.kind].cost}</b>`,`card:${c.id}`,'card')).join('') || '<small class="empty-hand">手牌已用尽，下回合抽一张。</small>'}</div>
  <div class="combat-log" aria-live="polite">${escape(s.log.at(-1))}</div>
  <div class="battle-controls">${rolling?`${button(!b.rolls?'投掷六骰':`重掷未保留骰子${b.enhanced&&b.rolls===2?' · −2♥':''}`,'roll','primary',b.rolls>=3||(b.rolls>0&&s.dice.every(d=>d.held)))}${button('收手 · 分配技能','allocate','secondary',!b.rolls)}`:`${button(b.used.length?'选择第二个技能':'返回投掷','back','secondary',b.used.length>0)}${button('结束回合 →','end','primary')}`}</div>
  <div class="battle-secondary">${button('应急防守 +3','emergency','text-btn',b.used.length>0)}${button(rolling?'跳过回合 →':SKILLS.some(k=>canSkill(s,k.id))?'仍有可用技能 · 可直接结束':'剩余骰子没有可用组合',rolling?'end':'noop','text-btn',!rolling)}${button('记录','log','text-btn')}</div>
  </section>`;}
function rewardInfo(r:Reward):{name:string;tag:string;icon:string;text:string;detail:string}{const s=state!;
  if(r.type==='relic'){const relic=RELICS.find(x=>x.id===r.id)!;return {name:relic.name,tag:`遗物 · ${relic.route}`,icon:relic.icon,text:relic.text,detail:'获得后整局生效，无需装备。'};}
  if(r.type==='upgrade'){const base=SKILLS.find(k=>k.id===r.skill)!,sk={...base,...UPGRADES[r.skill][r.branch]};return {name:sk.name,tag:`技能分支 · ${base.name}`,icon:'⚔',text:`${sk.cost.map(f=>FACE_NAME[f]).join(' + ')} → ${skillText(sk)}`,detail:'替换原技能；每个技能每局只能选择一个分支。'};}
  if(r.type==='modify'){const d=s.dice[r.die],faces=[...d.faces];faces[r.face]=r.to;return {name:`骰 ${r.die+1} · ${FACE_NAME[r.to]}之刻印`,tag:'骰面改造',icon:'⟐',text:`第 ${r.face+1} 面：${FACE_NAME[d.faces[r.face]]} → ${FACE_NAME[r.to]}。${FACE_NAME[d.faces[r.face]]}概率 −1/6，${FACE_NAME[r.to]}概率 +1/6。`,detail:`原：${d.faces.map(f=>FACE_NAME[f]).join(' ')}\n新：${faces.map(f=>FACE_NAME[f]).join(' ')}。下一场生效。`};}
  return {name:`${r.amount} 金币`,tag:'旅途补给',icon:'◉',text:'已无可用构筑奖励，收下盘缠继续前进。',detail:'直接加入本局金币。'};
}
function rewardCard(r:Reward,i:number,shop=false){const info=rewardInfo(r),sold=shop&&state!.bought.includes(i),invalid=!rewardLegal(state!,r);return `<article class="reward-card"><div class="reward-icon">${info.icon}</div><div><span class="eyebrow">${info.tag}</span><h2>${info.name}</h2><p>${info.text}</p><small>${escape(info.detail)}</small>${button(shop?sold?'已售出':`${price(r)} ◉ · 购买`:'选择这份力量 →',`${shop?'buy':'reward'}:${i}`,'secondary wide',sold||invalid||(shop&&state!.gold<price(r)))}</div></article>`;}
function rewardsView(){return `<section class="content-view"><span class="eyebrow">VICTORY · 战利品</span><h1>火种，更亮了一些。</h1><p class="muted">击败${ENEMIES[state!.battle!.enemy].name}。从下面选择一项，塑造你的下一场战斗。</p><div class="rewards">${state!.rewards.map((r,i)=>rewardCard(r,i)).join('')}</div><div class="flavor">「命运没有偏爱。只有你留下的骰子。」</div></section>`;}
function nodeView(){const s=state!;if(s.node==='shop')return `<section class="content-view"><span class="eyebrow">THE WANDERER · 行脚商人</span><h1>旅人，来挑点东西。</h1><p class="muted">「比起运气，我更相信准备。」持有 ${s.gold} 金币。</p>${s.stock.map((r,i)=>rewardCard(r,i,true)).join('')}<div class="offer"><b>暖身药剂</b><p>20 金币，恢复 12 生命。</p>${button('购买治疗 · 20 ◉','heal','secondary',s.gold<20||s.hp===s.maxHp)}</div>${button('离开商店 →','leave','primary wide')}</section>`;
  if(s.node==='camp')return `<section class="content-view camp"><span class="eyebrow">A MOMENT OF REST · 营地</span><div class="camp-art">♨</div><h1>火，还没有熄灭。</h1><p class="muted">在这里停留片刻。休息与磨炼，只能选择其一。</p><div class="offer"><b>靠近篝火</b><p>恢复 15 生命，当前 ${s.hp} / ${s.maxHp}。</p>${button('休息 · 恢复生命','rest','primary wide',s.hp===s.maxHp)}</div><div class="offer"><b>磨炼技艺</b><p>选择一个尚未升级的技能，获得永久分支。</p>${button('选择技能分支','train-menu','secondary wide',SKILLS.every(k=>s.upgrades[k.id]!==undefined))}</div>${button('继续赶路 →','leave','text-btn wide')}</section>`;
  return `<section class="content-view camp"><span class="eyebrow">THE EMBER ALTAR · 事件</span><div class="camp-art">✧</div><h1>灰烬中，有人在低语。</h1><p class="story">一座被遗忘的祭坛，仍在索取温热的血。石台的裂隙里，沉睡着不属于这个时代的力量。</p><div class="offer"><b>以血唤醒</b><p>失去 8 生命，获得一个尚未拥有的随机遗物。</p>${button('献上 8 生命 →','event:offer','primary wide',s.hp<=8||s.relics.length===12)}</div><div class="offer"><b>借一缕余温</b><p>恢复 8 生命，不获得遗物。</p>${button('温暖双手','event:heal','secondary wide')}</div>${button('转身离开','event:leave','text-btn wide')}</section>`;
}
function resultView(){const s=state!,won=s.screen==='won';return `<section class="content-view result"><span class="eyebrow">${won?'DEMO COMPLETE':'THE EMBER REMAINS'}</span><div class="result-emblem">${won?'♜':'⟐'}</div><h1>${won?'你重铸了命运。':'余烬，仍未散尽。'}</h1><p class="muted">${won?'铸命者倒下，地城终于迎来了一束光。':`倒在${escape(s.cause)}。带上这一局的经验，再试一次。`}</p><div class="result-grid"><div><b>${s.floor}/7</b><span>通过节点</span></div><div><b>${s.stats.turns}</b><span>战斗回合</span></div><div><b>${s.stats.double}</b><span>双技能回合</span></div><div><b>${s.stats.rerolls}</b><span>随机重掷</span></div></div><div class="summary"><h2>这次旅途的印记</h2><p>单招 ${s.stats.single} 回合 · 零招 ${s.stats.zero} 回合</p>${SKILLS.map(k=>`<div><span>${skillFor(s,k.id).name}</span><b>${s.stats.skills[k.id]} 次</b></div>`).join('')}</div>${button('查看本局构筑','build','secondary wide')}${button('再燃一次 · 开始新局','restart','primary wide')}${button('导出这次旅途','export','text-btn wide')}</section>`;}
function render(){document.body.classList.toggle('quick',settings.quick);app.className=state?.screen==='battle'?'in-battle':'';app.innerHTML=state?`${header()}${stats()}${saveWarning?`<div class="warning compact">${saveWarning}</div>`:''}${state.screen==='map'?mapView():state.screen==='battle'?battleView():state.screen==='reward'?rewardsView():state.screen==='node'?nodeView():resultView()}`:home();}
function help(){open(`<h2>六骰，两招，一次抉择。</h2><ol class="help"><li><b>首次投掷六枚骰子。</b>点击骰子保留，未保留的可同时重掷，最多两次。</li><li><b>收手，分配技能。</b>每个技能消耗指定组合的骰子。一回合最多两招，同名技能只能一次。</li><li><b>先看意图，再做选择。</b>敌人在你之后行动。格挡抵消伤害，下回合清空。</li><li><b>战术牌在首招前打。</b>先改骰、加伤或护甲；发动第一招后就不能再改骰或打牌。</li><li><b>没有好组合也能过。</b>应急防守获得 3 格挡并结束回合；发动主技能后不能使用。</li></ol><div class="example"><b>剑剑剑盾盾焰</b><p>重斩用掉「剑剑剑焰」，架盾用掉剩下的「盾盾」。两招各用各的骰子。</p></div><p class="muted">起始祝福：15 金币旅途盘缠。生命跨战斗保留；战术牌与战术点每场重置。</p>${button('明白了','close','primary wide')}`);}
function menu(){open(`<h2>旅途手记</h2><div class="menu-list">${button('玩法与规则','help','secondary wide')}${button(settings.sound?'声音：开':'声音：关','sound','secondary wide')}${button(settings.quick?'快速模式：开':'快速模式：关','quick','secondary wide')}${button('导出存档'+(corrupt?'（原文件）':''),'export','secondary wide',!state&&!corrupt)}${button('导入存档','import','secondary wide')}${state?button('结束当前旅途，重新开始','restart','secondary wide'):''}</div><p class="muted">v0.2.0 · 单幕 Demo<br>${offlineReady?'离线资源已缓存':'离线缓存等待首次成功加载（需 localhost 或 HTTPS）'}<br>${saveWarning||'有效动作自动保存在此浏览器。'}<br>导入进度会替换当前旅途，请先导出需要保留的存档。</p>`);}
function buildView(){if(!state)return;open(`<h2>余烬骑士 · 本局构筑</h2><h3>遗物 ${state.relics.length} / 12</h3>${state.relics.map(id=>{const r=RELICS.find(r=>r.id===id)!;return `<div class="build-item"><b>${r.icon} ${r.name}</b><p>${r.text}</p></div>`;}).join('')||'<p class="muted">尚未获得遗物。战后奖励、祭坛与商店都可能带来新的力量。</p>'}<h3>技能分支</h3>${SKILLS.filter(k=>state!.upgrades[k.id]!==undefined).map(k=>`<div class="build-item"><b>${k.name} → ${skillFor(state!,k.id).name}</b><p>${skillText(skillFor(state!,k.id))}</p></div>`).join('')||'<p class="muted">还未升级技能。</p>'}<h3>骰面改造 ${state.dice.filter(d=>d.modified).length} / 3</h3>${state.dice.map(d=>`<div class="die-inspect"><b>骰 ${d.id+1}${d.modified?' ◈':''}</b><span>${faceRow(d.faces)}</span></div>`).join('')}<p class="muted">每个面概率均为 1/6。每枚骰子最多改造一次，每局最多三枚。</p>`);}
function showSkill(id:SkillId){const s=state!,sk=skillFor(s,id),b=s.battle!,ids=payment(s,id);selection={kind:'skill',id,dice:ids||[]};const possible=canSkill(s,id);open(`<span class="eyebrow">${s.upgrades[id]===undefined?'骑士技艺':'已升级技艺'}</span><h2>${sk.name}</h2><p class="muted">${sk.flavor}</p><div class="skill-detail"><span class="cost">${faceRow(sk.cost)}</span><b>${skillText(sk)}</b></div>${possible?'<p>将消耗以下骰子。点击可调整同符号骰子的选择：</p>':`<p class="warning">${!b.rolls?'请先投掷六骰。':b.used.includes(id)?'本回合已经使用过这项技能。':b.phase==='roll'?'请先点击「收手 · 分配技能」。':`缺少：${missing(id)}`}</p>`}<div id="payment-dice"></div><div id="payment-preview"></div>${button('确认发动','confirm-skill','primary wide',!possible)}${button('取消，继续思考','close','text-btn wide')}`);selection={kind:'skill',id,dice:ids||[]};updatePayment();}
function updatePayment(){if(selection?.kind!=='skill')return;const sel=selection,s=state!,e=preview(s,sel.id,sel.dice);document.querySelector('#payment-dice')!.innerHTML=`<div class="dice-tray mini">${s.dice.map(d=>button(`${symbolHTML(symbol(d))}<small>${d.spent?'已用':`骰 ${d.id+1}${sel.dice.includes(d.id)?' ✓':''}`}</small>`,`pay:${d.id}`,`die ${sel.dice.includes(d.id)?'held':''}`,d.spent||!canSkill(s,sel.id))).join('')}</div>`;document.querySelector('#payment-preview')!.innerHTML=`<div class="example">${e.damage?`伤害 ${e.damage}${e.pierce?'（穿透）':''} · `:''}获得 ${e.block} 格挡${e.extra?` · 附带 ${e.extra} 伤害`:''}<br>敌人预计失去 ${Math.min(s.battle!.hp,e.loss)} 生命<br>若现在结束回合，预计受到 ${incoming(s,e.block)} 伤害${e.next?`<br>本回合下一次攻击 +${e.next}`:''}</div>`;}
function showCard(id:number){const s=state!,b=s.battle!,c=b.hand.find(c=>c.id===id)!;if(!c)return;const cfg=CARDS[c.kind],allowed=b.rolls>0&&!b.used.length&&b.cardsUsed<2&&b.tp>=cfg.cost;open(`<span class="eyebrow">战术牌 · ${cfg.cost} 战术点</span><h2>${cfg.name}</h2><p>${cfg.text}</p>${cfg.target?`<p>选择目标骰子</p><div id="card-dice"></div>`:''}${c.kind==='calibrate'?'<div id="card-faces"></div>':''}${!allowed?'<p class="warning">需要首掷完成、尚未出招、战术点足够，且本回合未用满两张牌。</p>':''}${button('确认使用','confirm-card','primary wide',!allowed)}${button('取消','close','text-btn wide')}`);selection={kind:'card',id,die:0,face:'sword'};updateCard();}
function updateCard(){if(selection?.kind!=='card')return;const sel=selection;const dice=document.querySelector('#card-dice');if(dice)dice.innerHTML=`<div class="dice-tray mini">${state!.dice.map(d=>button(`${symbolHTML(symbol(d))}<small>骰 ${d.id+1}</small>`,`target:${d.id}`,`die ${sel.die===d.id?'held':''}`,d.spent)).join('')}</div>`;const faces=document.querySelector('#card-faces');if(faces)faces.innerHTML=`<p>改为哪个符号？</p><div class="face-choices">${(['sword','shield','fire'] as Face[]).map(f=>button(`${symbolHTML(f)} ${FACE_NAME[f]}`,`face:${f}`,`secondary ${sel.face===f?'selected':''}`)).join('')}</div>`;}
function exportSave(){const text=corrupt||(state?serialize(state):null);if(!text)return;const url=URL.createObjectURL(new Blob([text],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download=`余烬之旅-${state?.runId||'原始存档'}.json`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function handle(action:string){const [kind,arg]=action.split(':');
  if(kind==='close'){close();return;}if(kind==='noop')return;
  if(kind==='menu'){menu();return;}if(kind==='help'){help();return;}
  if(kind==='sound'||kind==='quick'){settings[kind]=!settings[kind];try{localStorage.setItem(PREF,JSON.stringify(settings));}catch{/* Settings remain for this session. */}render();menu();return;}
  if(kind==='export'){exportSave();return;}if(kind==='import'){document.querySelector<HTMLInputElement>('#import-file')!.click();return;}
  if(kind==='restart'||(kind==='new'&&corrupt)){open(`<h2>开始新的旅途？</h2><p>当前的局内进度将被替换。需要保留时，请先导出存档。</p>${button('先导出存档','export','secondary wide')}${button('确认开始新局','confirm-new','primary wide')}${button('继续当前旅途','close','text-btn wide')}`);return;}
  if(kind==='new'||kind==='confirm-new'){corrupt=null;persist(newRun());close();render();return;}
  if(!state)return;
  if(kind==='build'){buildView();return;}
  if(kind==='boss-info'||kind==='enemy-info'){const e=ENEMIES[kind==='boss-info'?'boss':state.battle!.enemy];open(`<span class="eyebrow">敌人图鉴</span><h2>${e.name}</h2><p>${e.lore}</p><ol class="help">${e.cycle.map(i=>`<li><b>${i.name}</b>：${i.attacks.length?i.attacks.join(' + ')+' 普通伤害':i.block?`获得 ${i.block} 格挡`:'不造成伤害'}</li>`).join('')}</ol><p class="muted">按上述顺序循环，意图在每个玩家回合开始时固定。</p>`);return;}
  if(kind==='log'){open(`<h2>战斗记录</h2><ol class="help">${state.log.map(t=>`<li>${escape(t)}</li>`).join('')}</ol>`);return;}
  if(kind==='skill'){showSkill(arg as SkillId);return;}if(kind==='card'){showCard(Number(arg));return;}
  if(kind==='pay'&&selection?.kind==='skill'){const id=Number(arg);selection.dice=selection.dice.includes(id)?selection.dice.filter(x=>x!==id):[...selection.dice,id];updatePayment();return;}
  if(kind==='target'&&selection?.kind==='card'){selection.die=Number(arg);updateCard();return;}
  if(kind==='face'&&selection?.kind==='card'){selection.face=arg as Face;updateCard();return;}
  if(kind==='confirm-skill'&&selection?.kind==='skill'){act({type:'skill',skill:selection.id,dice:selection.dice});return;}
  if(kind==='confirm-card'&&selection?.kind==='card'){act({type:'card',id:selection.id,die:selection.die,face:selection.face});return;}
  if(kind==='train-menu'){open(`<h2>选择一项技能分支</h2>${SKILLS.filter(k=>state!.upgrades[k.id]===undefined).map(k=>`<h3>${k.name}</h3>${UPGRADES[k.id].map((u,i)=>button(`<b>${u.name}</b><small>${skillText({...k,...u})} · ${({...k,...u}).cost.map(f=>FACE_NAME[f]).join('')}</small>`,`train:${k.id}:${i}`,'upgrade-option secondary wide')).join('')}`).join('')}`);return;}
  if(kind==='train'){act({type:'train',skill:arg as SkillId,branch:Number(action.split(':')[2]) as 0|1});return;}
  if(['enter','reward','buy'].includes(kind)){act({type:kind as 'enter'|'reward'|'buy',index:Number(arg)});return;}
  if(kind==='die'){act({type:'hold',die:Number(arg)});return;}
  if(kind==='event'){act({type:'event',choice:arg as 'offer'|'heal'|'leave'});return;}
  if(['roll','allocate','back','end','emergency','rest','leave','heal'].includes(kind))act({type:kind} as Action);
}
document.addEventListener('click',e=>{const button=(e.target as Element).closest<HTMLButtonElement>('button[data-action]');if(button&&!button.disabled)handle(button.dataset.action!);});
modal.addEventListener('cancel',()=>{selection=null;});
document.querySelector<HTMLInputElement>('#import-file')!.addEventListener('change',async e=>{
  const input=e.target as HTMLInputElement,file=input.files?.[0];input.value='';if(!file)return;
  try{if(file.size>200000)throw new Error('存档文件过大。');const candidate=deserialize(await file.text());open(`<h2>导入旅途？</h2><p>第 ${Math.min(candidate.floor+1,7)} 层 · ${candidate.hp} 生命 · ${candidate.gold} 金币。导入后会替换当前进度。</p>${button('先导出当前存档','export','secondary wide',!state&&!corrupt)}<button id="confirm-import" class="primary wide">确认导入</button>${button('取消','close','text-btn wide')}`);document.querySelector('#confirm-import')!.addEventListener('click',()=>{persist(candidate);corrupt=null;close();render();notify('存档已恢复。');},{once:true});}catch(error){notify(error instanceof Error?error.message:'导入失败，当前进度没有改变。');}
});
render();
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').then(()=>navigator.serviceWorker.ready).then(async()=>{offlineReady=await caches.has('ember-demo-0.2.0');}).catch(()=>{/* LAN HTTP cannot register a service worker; online play remains available. */});
